BrenoHenrike/Scripts

Scripts/CoreFarms.cs
DreadFireREP
DruidGroveREP
DwarfholdREP
EtherStormREP
HorcREP
InfernalArmyREP
=> Adding several reputation farms

Scripts/Nulgath/CoreNulgath.cs, Scripts/Nulgath/EvolvedOrb.cs, Scripts/Story/DarkAlliance.cs, Scripts/Story/SeraphicWar.cs
Bot for getting Evolved Blood,Hex,Shadow Orb pet
=> Add Evolved Blood,Hex,Shadow Orb pet

Scripts/CoreFarms.cs
=> ADD Death Pit Arena REP and Faerie Court

Scripts/Farm/REP/FaerieCourtREP.cs
=> ADD Faerie Court Rep

Scripts/Story/ThroneofDarkness/01CastleofBones.cs
=> Create  Directory for Throne Of Darkness

CoreFarms.cs
Update join for Chaos Militia and Update quests for BaconCat
=> Update BaconCat and Chaos Militia

Story/PyramidofPain.cs
Bonus Member Chaos Finale Saga
=> Create Pyramid of Pain script

Story/KillerCatacombs.cs
Bonus Member Chaos Finale Saga
=> Create Killer Catacombs script

Nulgath/Various/PurifiedClaymoreOfDestiny.cs
=> Small typo fix in Taro Manslayers

CoreBots.cs, Evil/ADK.cs, Evil/Vordred Amor - Evil.cs
Q4 "Ultimate Darkness Gem" was set as isTemp
=> new() Simplifications and fix for ADK

Skills/AdvancedSkills.txt
Added SSOT Atk and Def skillset and variants.
=> Updated AdvancedSkills.txt

Darkon/CoreDarkon.cs, Prototypes/PrinceDarkonsPoleaxePreReqs.cs
- Added Prince Darkon's Poleaxe Pre-requisite bot.
- Added Darkon's Instant Noodle buy bot to CoreDarkon.
- Added some supplementary Core.Logger lines to CoreDarkon.
=> Created/Modified some Darkon Scripts

Prototypes/OdditiesMerge[CursedDollTassel].cs, Prototypes/OdditiesMerge[OddCoin+EctoplasmicToken].cs, Prototypes/OdditiesMerge[SpookyFabricScrap+EerieEmbellishment].cs
- Created Merge for Odd Coins + Ectoplasmic Tokens
- Created Merge for Spooky Fabric Scraps + Eerie Embellishments
=> Created Moar Oddities Merge

Prototypes/QueenReign.cs, Prototypes/QueenReignMerge[AncientHourglass].cs
Created 2 bots for "Queen Reign Merge Quest" request by DepressedFaggot#0420
=> Created QueenReignMerge and QueenReign Storyline Bot.

NulgathDiamondMerge.cs
Fixed Silver Tower and Mirror Mirror quest
=> Throne of Darkness Fix

Story/Banished.cs
Added correct items for collection. Not just collect "Item 0/1"
=> Fix Item pick up for "An Enemy Unblooded

CoreDailies.cs
Added rule to purchase class after reaching the required 84 tokens
=> Pyro and Cryo changes

Story/TitanAttack.cs
Added the new quests to this - spans over 3 maps in total. Tested it and it works, don't know if the script structure is fine - should be (hopefully).
=> Added new maps questlines

Other/MergeShops/ShadowflameFinaleMerge.cs, Story/Ruinedcrown.cs
might've accidently closed my last pull request trying to update it (:
=> ruinedcrown

Other/MergeShops/ArchFiendWarlordMerge.cs
added gold farm and correct merge mat purchase
=> Fixing Unidentified 25 not buying

CoreBots.cs, Other/MergeShops/BloodMoonVampireMerge.cs, Other/MergeShops/BloodWarLycanMerge.cs, Story/BloodMoon.cs
Added the merge of Blood War Lycan
Added the merge of Blood War Vampire
Added the Blood Moon Saga
=> Blood War Lycan Merge, Blood War Vampire Merge and Blood Moon Saga

Nation/CoreNation.cs
Shouldn't need to add Escherion's Helm, Sword or Hydra Scale Piece because their functions add that..right?
=> Added missing AddDrop

CoreDailies.cs
Added buy item for DeathKnight Lord
=> Added buy item for DeathKnight Lord

.gitignore, Army/ArmyLRFull.cs, Legion/CoreLegion.cs
Need to handle splitting party into 2 for aggromon evil rep farming in 3s and for LF1 shadowrealmpast/revenant maps
=> Full army LR script

Army/ArmyLRFull.cs, Army/Various/ArmyLegionToken.cs
ArmyLegionToken missing buyitem for undead champion to be able to accept the quest for dreadrock lts
=> Diamond Token of Dage and other prefarm fixes
